[project]
name = "quantum-diffusion"
version = "0.1.0"
description = ""
authors = [
    { name = "Jan Smółka", email = "jp.smolka@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.2",
    "flax>=0.12.0",
    "jax>=0.7.1",
    "pennylane>=0.44.0",
    "quantum-image-encoding"
]

[tool.uv.sources]
quantum-image-encoding = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
