[project]
name = "quantum-datasets"
version = "0.1.0"
description = ""
authors = [
    { name = "Jan SmÃ³Å‚ka", email = "jp.smolka@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jax>=0.6.2",
    "grain>=0.2.15",
    "scikit-learn>=1.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
