[project]
name = "quantum-image-encoding"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Jan SmÃ³Å‚ka", email = "jp.smolka@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
